# Generated by Django 5.1.4 on 2025-01-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_specialty_trainer_delete_fitnessclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='specialties',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialties',
            field=models.CharField(default='Generalist', max_length=200),
        ),
    ]
