# Generated by Django 5.1.4 on 2025-01-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
